[package]
name = "v2m-evaluator"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
v2m-formats = { path = "../core/formats" }
v2m-nir = { path = "../core/nir" }
thiserror = { workspace = true }
